title: Médecin Généraliste Buros
description: Ulysse Paultre, médecin généraliste à Buros
author: Docteur Ulysse Paultre
about: Médecin Généraliste à Buros


baseurl: "medecin-buros"
url: "http://localhost:4000"
permalinks: pretty

allowsearch: true

google_analytics: UA-72862926-

share:


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]